import type { Metadata } from "next";
import "./globals.scss";
import { Space_Grotesk, Outfit } from 'next/font/google';

export const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['700'],
  variable: '--font-space-grotesk',
});

export const outfit = Outfit({
  subsets: ['latin'],
  weight: ["400"],
  variable: '--font-outfit',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-space-grotesk font-normal ${spaceGrotesk.variable} ${outfit.variable}`}>{children}</body>
    </html>
  );
}
